# Generated by Django 5.2.12 on 2026-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focussession',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='focussession',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='focussession',
            name='focus_type',
        ),
        migrations.RemoveField(
            model_name='focussession',
            name='started_at',
        ),
        migrations.AddField(
            model_name='focussession',
            name='date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='focussession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
